services:
  backend:
    container_name: taskmanager-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development

  frontend:
    container_name: taskmanager-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
